/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_relgames_clocktest_NativeRdstc */

#ifndef _Included_org_relgames_clocktest_NativeRdstc
#define _Included_org_relgames_clocktest_NativeRdstc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_relgames_clocktest_NativeRdstc
 * Method:    rdstc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_relgames_clocktest_NativeRdstc_rdstc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
